version: '3.8'

services:
  # 開発用Next.jsアプリケーション（ホットリロード付き）
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: shift-management-ai-dev
    ports:
      - "3000:3000"
    environment:
      # 基本設定
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      
      # Firebase設定
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
      
      # Vertex AI設定
      - VERTEX_AI_PROJECT_ID=${VERTEX_AI_PROJECT_ID}
      - VERTEX_AI_LOCATION=${VERTEX_AI_LOCATION:-us-central1}
      
      # LINE API設定
      - LINE_CHANNEL_ACCESS_TOKEN=${LINE_CHANNEL_ACCESS_TOKEN}
      - LINE_CHANNEL_SECRET=${LINE_CHANNEL_SECRET}
      
      # NextAuth設定
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
    
    env_file:
      - .env.local
    
    volumes:
      # ホットリロード用のファイルマウント
      - .:/app
      - /app/node_modules
      - /app/.next
    
    networks:
      - app-network
    
    restart: unless-stopped
    
    # 開発用のヘルスチェック
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s

  # Firebase Emulator（開発用）
  firebase-emulator:
    image: node:20-slim
    container_name: firebase-emulator-dev
    ports:
      - "4000:4000"  # Firebase Emulator UI
      - "8080:8080"  # Firestore Emulator
      - "9099:9099"  # Auth Emulator
      - "5001:5001"  # Functions Emulator
    environment:
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID:-demo-project}
    volumes:
      - .:/app
      - firebase_dev_data:/app/.firebase
    working_dir: /app
    command: >
      sh -c "
        apt-get update && apt-get install -y curl &&
        npm install -g firebase-tools &&
        firebase emulators:start --only firestore,auth,functions --project ${FIREBASE_PROJECT_ID:-demo-project}
      "
    networks:
      - app-network
    restart: unless-stopped

# 永続化ボリューム
volumes:
  firebase_dev_data:
    driver: local

# ネットワーク設定
networks:
  app-network:
    driver: bridge