version: '3.8'

services:
  # Firebase Emulator Service
  firebase-emulator:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: firebase-emulator
    container_name: firebase-emulator
    ports:
      - "4000:4000"  # Emulator UI
      - "8080:8080"  # Firestore
      - "9099:9099"  # Auth
    volumes:
      - .:/app
      - firebase_data:/app/.firebase
    environment:
      - FIREBASE_PROJECT_ID=shift-management-ai
      - FIREBASE_TOKEN=${FIREBASE_TOKEN:-}
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Next.js Application Service
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: app-dev
    container_name: shift-management-ai-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - FIRESTORE_EMULATOR_HOST=firebase-emulator:8080
      - FIREBASE_AUTH_EMULATOR_HOST=firebase-emulator:9099
      - FIREBASE_PROJECT_ID=shift-management-ai
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      firebase-emulator:
        condition: service_healthy
    networks:
      - app-network

volumes:
  firebase_data:

networks:
  app-network:
    driver: bridge