version: '3.8'

services:
  # Next.js Application Service (本番環境ベース)
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: runner
    container_name: shift-management-ai-dev
    ports:
      - "3000:3000"
    volumes:
      # 開発用：ソースコードをマウント（ホットリロード）
      - .:/app
      - /app/node_modules
      # .nextディレクトリは除外してコンテナ内で作成
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=3000
    restart: unless-stopped
    networks:
      - app-network
    # ヘルスチェック
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app-network:
    driver: bridge